### ISSUE TITLE
Strange Reply from commands:

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailShop#10]
From JailSet:
 [jail.shop] Use: sm_jailset <#userid|name> [amount]
 Use: sm_jailset <#userid|name> [amount]
From JailGive:
[{green}jail.shop{default}] Use: sm_jailgive <#userid|name> [amount]
 [jail.shop] Use: sm_jailgive <#userid|name> [amount]
(I get doble answers)

**Comment by shanapu** [comment]
oO 
first look i would say you got myjailshop running two times. 
A dev and a master branch...:

`[jail.shop] Use: sm_jailset <#userid|name> [amount]`  -  master
`Use: sm_jailset <#userid|name> [amount]`  -  dev

`[{green}jail.shop{default}] Use: sm_jailgive <#userid|name> [amount]`  -  master
`[jail.shop] Use: sm_jailgive <#userid|name> [amount]`  -  dev

**Comment by Hexer10** [comment]
Thanks, I'm stupid there was 2 myjbshop file one named myjailbreak.smx and the other MyJailBreak.smx,
habitued with windows that cant be 2 files with the same name including CAPS (The server is hosted on linux.)
