### ISSUE TITLE
AWP+Deagle full charged

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailShop#11]
If I have another weaps (primary or secondary) if i shop an AWP with one bullet/deagle with 1mag they get dropped on the groud and they got full charged.
ES: I've got 1deagle and 1ak, I shop AWP + DEAGLE and they get with all ammos.

**Comment by shanapu** [comment]
yeah I can reproduce this! thanks for reporting.
Will fix this when I got time. 
Should the weapon (in your example the ak) disappear or stay on ground? what is your opinion?

**Comment by Hexer10** [comment]
For me is best get the weapons that i have on the ground also an CVar isn't a bad idea.

**Comment by shanapu** [comment]
fixed with latest version.
new cvar `sm_jailshop_removeweapon - 0 - disabled, 1 - When a player already got a prim/sec weapon and buy deagle or awp the current weapon disappear`
