### ISSUE TITLE
Disable shop on LR

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailShop#12]
There is a way to disable shop when there is the LR(LastRequest form SM_Hosties?), beacause i don't want the player use gravity on gun toss etc...
For both(Ts and CTs) when there is the LR time.
Thanks

**Comment by shanapu** [comment]
disabled buying in shop or deactivate buyed shop items on lr?
I think i will make cvars for both

**Comment by Hexer10** [comment]
For me is better disable the shopped items, a CVars isn't a bad idea.

**Comment by shanapu** [comment]
I saw there was already a part to reset player perks(gravity...) on LR, but it was a bit bugged. Now fixed.
Also two new cvars
 *  new cvar - sm_jailshop_buy_lr - 0 - disabled, 1 - Restrict shopping on last request
 *  new cvar - sm_jailshop_remove_lr - 0 - disabled, 1 - Remove the bought perks on a last request. (bought weapons stay)

**Comment by Hexer10** [comment]
If shopped items are disabled when a player **reach** the LR or **start** an LR with a guard?

**Comment by shanapu** [comment]
> player reach the LR

**Comment by Hexer10** [comment]
Can I tell here to you that i forgot to translate to IT Line: 55
https://github.com/shanapu/MyJailShop/compare/dev...Hexer10:patch-1

**Comment by shanapu** [comment]
everything fine with topic? can we close this?

thanks again for the 'it' fix!
