### ISSUE TITLE
Add admin command in admin menu

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailShop#14]
1)Add admin command in admin menu
2)Add translate phrase "shop_onlyct"

**Comment by shanapu** [comment]
> 1)Add admin command in admin menu

good idea! will do it soon.

> 2)Add translate phrase "shop_onlyct"

oh, there is something missing... thx for report! will be fixed soon

But please, here on myjailshop the same as on myjailbreak:
**Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!**

**Comment by shanapu** [comment]
I've become aware, that it's kind of useless to add admin commands like !jailgive / !jailset in admin menu, even when I put a select menu for players after this command, you have to set/type the amoung of credits on chat.
