### ISSUE TITLE
terrorist shop doesnt work

### ISSUE THREAD

**Issue by valantislevas** [shanapu/MyJailShop#16]
SourceMod Version Information:
    SourceMod Version: 1.8.0.5954
version metamod
Protocol version 13563 [418/418]
Exe version 1.35.6.3 (csgo)
Exe build: 10:31:20 Dec 13 2016 (6605) (730)

i use the latest stable 1.20 version 
but the terrorist shop doesnt work ct and other thing is ok.. no error message..

**Comment by valantislevas** [comment]
i see that: 

L 12/18/2016 - 16:29:58: server_cvar: "mp_friendlyfire" "1"
L 12/18/2016 - 16:29:59: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/18/2016 - 16:29:59: [SM] Blaming: myjailshop.smx
L 12/18/2016 - 16:29:59: [SM] Call stack trace:
L 12/18/2016 - 16:29:59: [SM]   [0] ConVar.BoolValue.get
L 12/18/2016 - 16:29:59: [SM]   [1] Line 1582, addons/sourcemod/scripting/myjailshop.sp::Menu_OpenShop
L 12/18/2016 - 16:29:59: [SM]   [2] Line 538, addons/sourcemod/scripting/myjailshop.sp::Command_Menu_OpenShop

**Comment by valantislevas** [comment]
its works ok version 1.0 of plugin 1.2 have that issue

**Comment by shanapu** [comment]
https://forums.alliedmods.net/showthread.php?p=2478848#post2478848

> hi, I think I found the bug. 
Do I assume right, you use an warden plugin from ecca, ESK0, zipcore or else and not MyJailbreaks warden?
Will push update soon.
