### ISSUE TITLE
about sql table and infos

### ISSUE THREAD

**Issue by valantislevas** [shanapu/MyJailShop#17]
Hello is possible to make it work with the field accountid? to work only with steamid?
i am going to transfer steamids/credits from other plugin with yours and it will be useful if that is possible.. 
otherwise i will convert steamids to steamid3 to make it work

**Comment by shanapu** [comment]
Can I ask you, which plugins credits you wanna transfer to myjailshop?
Would this be helpful for other server operators? Or just for you in this special case?

If you can do this for yourself I would be very happy.
But when many people will ask for this I'll probably do it sometime.

**Comment by valantislevas** [comment]
hello, thanks for the reply.. i used untill now that plugin https://forums.alliedmods.net/showthread.php?t=247917 jail shop and i convert the sq3 to sql file and i edit it and  move it in your database to make it work.. 
if sometime want to do something that will be great.. also i recommend that if you make a table extra or something that you log of the spend credits for review in cases if someone have problem per accountid

thanks

**Comment by valantislevas** [comment]
also is possible to edit the table with credits and make the plugin work? because if i edit my credits and join after it says 0 it saves after disconnect.. also if i disable the save after disconnect the credits will be lost after server rr or something? @shanapu ?

**Comment by shanapu** [comment]
hi, sry for late response.
> also i recommend that if you make a table extra or something that you log of the spend credits for review in cases if someone have problem per accountid

MyJailShop already log purchases & gifts of a player in a log file.
`"sm_jailshop_log" - "1" - "Allow MyJailShop to log purchases and gifts in logs/MyJailShop"`

> also is possible to edit the table with credits and make the plugin work? because if i edit my credits and join after it says 0 it saves after disconnect.. also if i disable the save after disconnect the credits will be lost after server rr or something? @shanapu ?

The plugin works. You can edit the credits of a player in the mysql database when player is not on the server. 
`"sm_jailshop_mysql" - "0" - "0 - disabled, 1 - Should we use a mysql database to store credits"`

It saves the credits after a mapchange, serverrestart &/or disconnect. `sm_jailshop_credits_save" - "1" - "0 - disabled, 1 - Save credits on player disconnect`

**Comment by shanapu** [comment]
I assume you sort your problems... I close this. 

if you still got problems, open a new issue or comment here.
