### ISSUE TITLE
two server with same database

### ISSUE THREAD

**Issue by valantislevas** [shanapu/MyJailShop#18]
because i have 2 jailbreak servers with store zephyrus credits system and myjailshop for shoping on different host.. i copied the files and is working but something make conflict.. if in one server have some credits if i connect to other server and disconnect the credits in db is "0" is possible somehow to make it work.. if i play on #1 server and disconnect when i connect to other server #2 to have the same ?

**Comment by shanapu** [comment]
MyJailShop works with a single database on more than one server, like you want.
If you use zephyrus credits system (or any other) `sm_jailshop_credits_system" - "0"` the credits will not been saved on myjailshops database. Be sure both servers connecting to the same zephyrus credits database.

**Comment by shanapu** [comment]
I assume you sort your problems... I close this. 

if you still got problems, open a new issue or comment here.
