### ISSUE TITLE
Discount/Sale shop items

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailShop#20]
Idea by Murr
I really like it, but not sure how to make it.
Discount on all items or just an single item or maybe a group of items?
How to start the discount? - random, every x rounds, per admin command or at a special time on the day?
How long the discount will go? - a round, a map or x minutes?

**Comment by VendeeMurr** [comment]
One day a week activates discount for all items and ends next day

**Comment by shanapu** [comment]
for the first, I implemented a sloppy sale. start/stop with `!sale` will discount all item - `sm_jailshop_sale_multi - How many percent discount on a sale!`
