### ISSUE TITLE
Disable shopped item while doing a TeamGames

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailShop#24]
Any way to get disabled the shopped items while get in a Team/Doing a "TeamMinigame",
and maybe give back the items after the minigame.

**Comment by shanapu** [comment]
I do this when i got time

**Comment by shanapu** [comment]
with 050404e I implement a reset for most perks, some still missing. Deagle, AWP & grenades stay on player without perk.

**Comment by shanapu** [comment]
Does it work as expected? Does it need improvements?

**Comment by Hexer10** [comment]
Sorry for very very late reply, as I saw the only bug is with the chicken, the player can still fly too if is in a team.

**Comment by shanapu** [comment]
my tests work without problems, everything like expect, can you confirm?
