### ISSUE TITLE
Futuristic Nades item / Items api?

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailShop#28]
[Futurist Granades](https://forums.alliedmods.net/showthread.php?p=2499362) as items.
https://github.com/shanapu/MyJailbreak/issues/205

Maybe api(natives/forwards) for add items?

**Comment by Hexer10** [comment]
Yeah, it would be awesome to add that nades in the shop but I think should nerfed because, if I thrown a black hole or a forcefield inside a marker with +10Ts ...

**Comment by shanapu** [comment]
With the new Item API It's very easy to add these grenades to shop. 
I never played with these plugin/grenades, only know them from video. 
And like you say, right now the nades are overpowered.
So I won't do this yet.

> I think should nerfed 
maybe when there a natives to configure grenade parameters.
