### ISSUE TITLE
Gift yourself credits

### ISSUE THREAD

**Issue by TiBarification** [shanapu/MyJailShop#3]
We have a bug, that allows you to gift credits for yourself. I think it's bad idea.

**Comment by shanapu** [comment]
Could you explain the bug with more details? So I can reproduce  & fix it.

**Comment by TiBarification** [comment]
sm_jailgift #youruserid 1

**Comment by shanapu** [comment]
do i understand right. Gift credits to yourself is possible but there is no glitch/"cheat".
So Player got 500 credits and gift 50 credits to himself. he just got 500 credits not 550, right?
I will include a check so you can gift to yourself when im at home
