### ISSUE TITLE
Errors | Myjailshop frozdark shop

### ISSUE THREAD

**Issue by fkMain** [shanapu/MyJailShop#33]
LOGS:
L 07/01/2017 - 16:47:01: [SM] Blaming: shop.smx
L 07/01/2017 - 16:47:01: [SM] Call stack trace:
L 07/01/2017 - 16:47:01: [SM]   [0] ThrowNativeError
L 07/01/2017 - 16:47:01: [SM]   [1] Line 81, shop/player_manager.sp::PlayerManager_GetClientCredits
L 07/01/2017 - 16:47:01: [SM]   [3] Shop_GetClientCredits
L 07/01/2017 - 16:47:01: [SM]   [4] Line 52, addons/sourcemod/scripting/myjailshop-frozdark-shop.sp::MyJailShop_OnGetCredits
L 07/01/2017 - 16:47:01: [SM]   [6] Call_Finish
L 07/01/2017 - 16:47:01: [SM]   [7] Line 3465, addons/sourcemod/scripting/myjailshop.sp::Forward_OnGetCredits
L 07/01/2017 - 16:47:01: [SM]   [8] Line 3365, addons/sourcemod/scripting/myjailshop.sp::DB_WriteCredits
L 07/01/2017 - 16:47:01: [SM]   [9] Line 1472, addons/sourcemod/scripting/myjailshop.sp::OnClientCookiesCached
L 07/01/2017 - 16:47:01: [SM] Exception reported: Client index 1 is not in game

**Comment by shanapu** [comment]
this error belongs to R1KOs shop. "L 07/01/2017 - 16:47:01: [SM] Blaming: shop.smx"

 And this is an normal & harmless error, that just tell that a person just disconnected right after connecting and cookie chaching.
