### ISSUE TITLE
Credits bug

### ISSUE THREAD

**Issue by SpaceBanana7** [shanapu/MyJailShop#35]
Hi,  
I had a problem with your plugin "MyJailShop";
 I've swapped all the things on another vps but now when for example, I gift something and restart the map it reset the credits at 6453  the ones who I had on the other vps.
(And to the players who has joined the first time, its doesn't save the credits who they've got)
 Which is the file where the credits are going to be saved?

**Comment by shanapu** [comment]
sorry for the very late response. I don't know how could I miss this issue. Im very sorry.

MyJailshop can save the credits in two ways. 
On default the credits are save to sqlite 'aka clientprefs' - "sm_jailshop_mysql", "0".
You can find the sqllitefile with the data here:  `\csgo\addons\sourcemod\data\sqlite\clientprefs-sqlite.sq3`

The more advanced way is to setup a mysql database to store the credits there.  "sm_jailshop_mysql", "1".

Dont forget there is a cvar to disable the hole saving of credits and players start each map/connection from start "sm_jailshop_credits_save", "1" - save by default

I hope I could clarify you question even when it is 'too late'.
