### ISSUE TITLE
Tactical Shield coming back every round

### ISSUE THREAD

**Issue by skyprah** [shanapu/MyJailShop#38]
Currently the tactical shield comes back to the same Ct who purchased it even if he died. When he spawns it appears on his back every round, unless its purposely made to last the whole map?

I've also noticed the shield remaining on the CT during LR which could cause an unfair advantage, possibly equipping the shield and reequipping if they win they don't die.

**Comment by skyprah** [comment]
Shield is also staying on Prisoners when they have swapped to T side. I currently have shields set to CT only, and its remaining on the Ts back every round when he spawns.

**Comment by shanapu** [comment]
true, will make a fix later to remove shield after/when round/death/LR

**Comment by shanapu** [comment]
Just tested, works fine for me...

Have you seen and do you use the recommended config of tacticalshield for myjailshop?
https://keplyx.github.io/TacticalShield/installation.html

ts_keep_between_rounds **“0”**
ts_buytime **"-1"**
ts_price **“30000”**

and I recommend ts_shield_team **"1"** but should also work with default ts_shield_team **"0"**
