### ISSUE TITLE
Noclip stuck

### ISSUE THREAD

**Issue by TiBarification** [shanapu/MyJailShop#4]
If player uses noclip, and them he stucks in wall, could you do something with this?
Propose is to teleport player to free location or to someone of player.

**Comment by shanapu** [comment]
Yeah, this is known and is more or less indended.
I adopt the nostuck idea from the !dice plugin. In german server !dice is more populate than jailshop. And there is normaly the rule "!dice on own risk" which means when you get a disadvantage or getting stuck on noclip it's your own fault. "stuck on noclip? type kill in console!"
To use the noclip to get to armory you need to be skilled. If you fail and getting stuck I dont think you should get a compensation (teleport player to free location).

I think about a autokill feature if a player get stuck.

**Comment by shanapu** [comment]
can't find a clean and good way to check if player is stuck. code snippets i found are not reliable.

**Comment by shanapu** [comment]
I will add a convar to autoslay when player is stuck instead of a request "please type kill..."
