### ISSUE TITLE
Blackout.mp3 stuck

### ISSUE THREAD

**Issue by DolphinGamerYT** [shanapu/MyJailShop#40]
Hi,
I'm using MyJailShop and when I enter on server, downloads the files but gets stuck on blackout.mp3.
Any way to unstuck it?

**Comment by DolphinGamerYT** [comment]
![img_20180318_090910873](https://user-images.githubusercontent.com/31125786/37563944-46979c94-2a8c-11e8-8f27-5f55bc73d5e0.jpg)
In csgo, no errors in console.
I think I have fastdl correctly

**Comment by DolphinGamerYT** [comment]
Do you have discord or anything to talk?

**Comment by Hexer10** [comment]
We asked about the console log, not a screenshot

**Comment by DolphinGamerYT** [comment]
[SM] Changed cvar "sv_downloadurl" to "fountine.com/csgo/jailbreak1/".
L 03/18/2018 - 09:08:44: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_downloadurl") (value "fountine.com/csgo/jailbreak1/")
Unknown command "sm_motdgd_forced_duration"
L 03/18/2018 - 09:08:44: "DOLPHIN<3><STEAM_1:0:176105346><>" connected, address ""
Client "DOLPHIN" connected (192.168.1.54:27005).
L 03/18/2018 - 09:08:44: World triggered "Round_Start"
L 03/18/2018 - 09:08:44: [chat-processor.smx] Message formats generated for game 'csgo'.
L 03/18/2018 - 09:08:44: [chat-processor.smx] Successfully hooked a SayText2 chat hook.
L 03/18/2018 - 09:08:44: server_cvar: "sv_tags" "!gloves,!knife,!ws,128ticks,MyJailbreak,test"
L 03/18/2018 - 09:08:44: server_cvar: "sv_tags" "!gloves,!knife,!ws,128ticks,MyJailbreak,test"
L 03/18/2018 - 09:08:44: server_cvar: "sv_tags" "!gloves,!knife,!ws,128ticks,MyJailShop,MyJailbreak,test"
L 03/18/2018 - 09:08:44: server_cvar: "sv_tags" "!gloves,!knife,!ws,128ticks,MyJailShop,MyJailbreak,test"
L 03/18/2018 - 09:08:44: server_cvar: "sv_tags" "SM Hosties v2.2"
L 03/18/2018 - 09:08:45: "DOLPHIN<3><STEAM_1:0:176105346><>" STEAM USERID validated

**Comment by shanapu** [comment]
sry for late response. 
if this issue is still existing I would say it is a problem with you FastDL. Check you can access all files from your `sv_downloadurl` URL through browser

Is error still exist please open new issue or contact me on steam.
