### ISSUE TITLE
Incorrect rewarding

### ISSUE THREAD

**Issue by Include5** [shanapu/MyJailShop#41]
Terrorists get credits for winning the round if counter-terrorists win. Dead players get credits for winning the round, even if sm_jailshop_credits_win_alive "1"
Last dev
Last dev MyjailBreak
No error logs
SourceMod (1.9.0.6254) by AlliedModders LLC

> // This file was auto-generated by AutoExecConfig read and append beta
> // ConVars for plugin "myjailshop.smx"
> 
> 
> // 0 - disabled, 1 - enable the MyJailShop SourceMod plugin
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_enable "1"
> 
> // 1 - MyJailShop Credits, 0 - Zephrus store or 'SM Store' or FrozDark shop (need extra support plugin)
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_credits_system "1"
> 
> // 0 - disabled, 1 - Save credits on player disconnect
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_credits_save "1"
> 
> // 0 - disabled, 1 - Should we use a mysql database to store credits
> // -
> // Default: "0"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_mysql "1"
> 
> // Maximum of credits to earn for a player
> // -
> // Default: "50000"
> sm_jailshop_credits_max "50000"
> 
> // Minimum players to earn credits
> // -
> // Default: "4"
> // Minimum: "0.000000"
> sm_jailshop_minplayers "4"
> 
> // 0 - disabled, 1 - enable players get credits on warmup
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_warmupcredits "0"
> 
> // 0 - disabled, amount of credits a prisoner earns when kill a Guard
> // -
> // Default: "150"
> // Minimum: "0.000000"
> sm_jailshop_credits_kill_t "50"
> 
> // 0 - disabled, amount of credits a VIP prisoner earns when kill a Guard
> // -
> // Default: "200"
> // Minimum: "0.000000"
> sm_jailshop_credits_kill_t_vip "100"
> 
> // 0 - disabled, amount of credits a guard earns when kill a prisoner
> // -
> // Default: "15"
> // Minimum: "0.000000"
> sm_jailshop_credits_kill_ct "15"
> 
> // 0 - disabled, amount of credits a VIP guard earns when kill a prisoner
> // -
> // Default: "20"
> // Minimum: "0.000000"
> sm_jailshop_credits_kill_ct_vip "20"
> 
> // 0 - disabled, amount of credits a prisoner earns when win round
> // -
> // Default: "50"
> // Minimum: "0.000000"
> sm_jailshop_credits_win_t "25"
> 
> // 0 - disabled, amount of credits a VIP prisoner earns when win round
> // -
> // Default: "100"
> // Minimum: "0.000000"
> sm_jailshop_credits_win_t_vip "50"
> 
> // 0 - disabled, amount of credits a guard earns when win round
> // -
> // Default: "50"
> // Minimum: "0.000000"
> sm_jailshop_credits_win_ct "25"
> 
> // 0 - disabled, amount of credits a VIP guard earns when win round
> // -
> // Default: "100"
> // Minimum: "0.000000"
> sm_jailshop_credits_win_ct_vip "50"
> 
> // 0 - disabled, 1 - only alive player get credits when team win the round
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_credits_win_alive "1"
> 
> // 0 - disabled, amount of credits for reach last request as prisoner (only if hosties is available)
> // -
> // Default: "300"
> // Minimum: "0.000000"
> sm_jailshop_credits_lr "200"
> 
> // 0 - disabled, amount of credits for reach last request as prisoner (only if hosties is available)
> // -
> // Default: "400"
> // Minimum: "0.000000"
> sm_jailshop_credits_lr_vip "300"
> 
> // 0 - disabled, how many credits players receive every x seconds 'sm_jailshop_credits_time_interval'
> // -
> // Default: "5"
> // Minimum: "0.000000"
> sm_jailshop_credits_per_time "5"
> 
> // Time in seconds a player recieved credits per time
> // -
> // Default: "120"
> // Minimum: "0.000000"
> sm_jailshop_credits_per_time_interval "120"
> 
> // 0 - disabled, how many credits VIP players receive for 'sm_jailshop_credits_time_interval
> // -
> // Default: "10"
> // Minimum: "0.000000"
> sm_jailshop_credits_per_time_vip "10"
> 
> // 0 - disabled, 1 - welcome messages on spawn
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_welcome "1"
> 
> // 0 - disabled, 1 - enable chat notification everytime player get credits
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_notification "1"
> 
> // 0 - disabled, Time in seconds after roundstart shopping is allowed
> // -
> // Default: "180"
> // Minimum: "0.000000"
> sm_jailshop_buytime "180"
> 
> // 0 - disabled, 1 - only shopping until cell doors opened (only if smartjaildoors is available)
> // -
> // Default: "0"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_buytime_cells "0"
> 
> // 0 - disabled, 1 - restrict shopping on Last lequest
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_buy_lr "1"
> 
> // Remove the bought perks on a last request. (bought weapons will stay)
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_remove_lr "1"
> 
> // 0 - shop available for guards & prisoner, 1 - only prisoner
> // -
> // Default: "0"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_access "0"
> 
> // 0 - disable shopping on MyJailbreak Event Days, 1 - enable shopping on MyJailbreak Event Days (only if myjb is available)(show/gift/... credits is still enabled)
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_myjb "1"
> 
> // 0 - disabled, 1 - When a player already got a prim/sec weapon and buy deagle or awp the current weapon disappear
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_removeweapon "1"
> 
> // 0 - disabled, 1 - enable close menu after action
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_close "1"
> 
> // Allow "MyJailShop" to be added to the server tags? So player will find servers with MyJailShop faster. it dont touch you sv_tags
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_tag "1"
> 
> // Allow MyJailShop to log purchases and gifts in logs/MyJailShop
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_log "1"
> 
> // Set your custom chat commands for shop menu(!jailshop (no 'sm_'/'!')(seperate with comma ', ')(max. 12 commands)
> // -
> // Default: "jbshop,jbstore,jailstore"
> sm_jailshop_cmds_shop "jbshop,jbstore,jailstore,shop,manazin"
> 
> // Set your custom chat commands for gifting credits(!jailgift (no 'sm_'/'!')(seperate with comma ', ')(max. 12 commands)
> // -
> // Default: "jbgift,send"
> sm_jailshop_cmds_gift "jbgift,send"
> 
> // Set your custom chat commands for revive(!jailrevive (no 'sm_'/'!')(seperate with comma ', ')(max. 12 commands)
> // -
> // Default: "revive,jbrevive,alive"
> sm_jailshop_cmds_revive "revive,jbrevive,alive"
> 
> // Set your custom chat commands to see you credits (!jailcredits (no 'sm_'/'!')(seperate with comma ', ')(max. 12 commands)
> // -
> // Default: "points,credits"
> sm_jailshop_cmds_credits "points,credits"
> 
> // Set your custom chat commands for see all online players credits(!showjailcredits (no 'sm_'/'!')(seperate with comma ', ')(max. 12 commands)
> // -
> // Default: "showpoints,allcredits,showcredits"
> sm_jailshop_cmds_showcredits "showpoints,allcredits,showcredits"
> 
> // How many percent discount on a sale!
> // -
> // Default: "40"
> // Minimum: "1.000000"
> // Maximum: "100.000000"
> sm_jailshop_sale_multi "40"
> 
> // 0 - disabled, 1 - enable this MyJailShop Module
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_hud_enable "1"
> 
> // 0 - show hud only to alive player, 1 - show hud to dead & alive player
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_jailshop_hud_alive "1"
> 
> // x coordinate, from 0 to 1. -1.0 is the center
> // -
> // Default: "0.05"
> // Minimum: "-1.000000"
> // Maximum: "1.000000"
> sm_jailshop_hud_x "0.05"
> 
> // y coordinate, from 0 to 1. -1.0 is the center
> // -
> // Default: "0.65"
> // Minimum: "-1.000000"
> // Maximum: "1.000000"
> sm_jailshop_hud_y "0.65"
> 
> // Color of sm_hud_type '1' (set R, G and B values to 255 to disable) (Rgb): x - red value
> // -
> // Default: "200"
> // Minimum: "0.000000"
> // Maximum: "255.000000"
> sm_jailshop_hud_red "200"
> 
> // Color of sm_hud_type '1' (set R, G and B values to 255 to disable) (rGb): x - green value
> // -
> // Default: "200"
> // Minimum: "0.000000"
> // Maximum: "255.000000"
> sm_jailshop_hud_green "200"
> 
> // Color of sm_hud_type '1' (set R, G and B values to 255 to disable) (rgB): x - blue value
> // -
> // Default: "0"
> // Minimum: "0.000000"
> // Maximum: "255.000000"
> sm_jailshop_hud_blue "0"
> 
> // Alpha value of sm_hud_type '1' (set value to 255 to disable for transparency)
> // -
> // Default: "200"
> // Minimum: "0.000000"
> // Maximum: "255.000000"
> sm_jailshop_hud_alpha "200"

**Comment by shanapu** [comment]
thanks for reporting! I will investigate this issue asap!
