### ISSUE TITLE
SetPlayerAmmo (deagle) issue

### ISSUE THREAD

**Issue by 1DreaM1** [shanapu/MyJailShop#43]
Whenever I buy deagle, it's fully charged.
This issue appears since I've uploaded the latest myjailshop stable built.
I'm using: the latest sourcemod 1.9, the latest metamod 1.10 and also the latest stable MyJailbreak from 09/01/19.

This error code appears whenever someone buy deagle: 

> [SM] Exception reported: Property "m_iPrimaryReserveAmmoCount" not found (entity 180/weapon_deagle)  [SM] Blaming: myjailshop.smx
> [SM] Call stack trace:
> [SM] [0] SetEntProp
> [SM] [1] Line 248, /home/travis/build/shanapu/MyJailShop/addons/sourcemod/scripting/include/mystocks.inc::SetPlayerAmmo
> [SM] [2] Line 2477, addons/sourcemod/scripting/myjailshop.sp::Item_Deagle
> [SM] [3] Line 2217, addons/sourcemod/scripting/myjailshop.sp::Handler_Menu_OpenShop

Thanks for help.

**Comment by fzr87** [comment]
for me bug was tha who buy deagle not take money from him .

**Comment by shanapu** [comment]
Thank you for reporting.
This is CSGO right? Seems they removed `m_iPrimaryReserveAmmoCount` or there is another error in the code. I will investigate this.

**Comment by 1DreaM1** [comment]
yes csgo.

**Comment by 1DreaM1** [comment]
Something new ?

**Comment by Bara** [comment]
https://github.com/shanapu/MyJailShop/blob/4d2da1b73aead17e8130f89e8a6246c44d84193e/addons/sourcemod/scripting/include/mystocks.inc#L243
https://github.com/shanapu/MyJailShop/blob/4d2da1b73aead17e8130f89e8a6246c44d84193e/addons/sourcemod/scripting/include/mystocks.inc#L248-L249
Change Prop_Data to Prop_Send.

So far I know it still works fine (Example: [Silent AWP in TTT](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_silent_awp.sp#L167-L168)).

**Comment by 1DreaM1** [comment]
Thanks for help, works perfect.

**Comment by Hexer10** [comment]
I'll leave this open just to remember us to fix the issue in the main branch, If I have enough time I'll try to do it by tomorrow.
