### ISSUE TITLE
Cant compile zephyrus store

### ISSUE THREAD

**Issue by dzagu** [shanapu/MyJailShop#49]
//// myjailshop-zephyrus-store.sp
//
// C:\Users\Maciej\Desktop\kompiler\addons\sourcemod\scripting\include\store.inc(24) : error 050: constant 'szName' already defined
// C:\Users\Maciej\Desktop\kompiler\addons\sourcemod\scripting\include\store.inc(55) : error 050: constant 'iId' already defined
// C:\Users\Macie

**Comment by shanapu** [comment]
zephyrus store is not compatible to sourcemod 1.10. **I had to remove zeph and darkfroz store support within latest update!**

compile old myjs version with an older compiler 1.9
