### ISSUE TITLE
Logs for purchases and gifts.

### ISSUE THREAD

**Issue by Weeeishy** [shanapu/MyJailShop#6]
Hello,

Is it possible to log these actions? It would be helpful to track down people that are farming credits and spending them quickly so no one notices or even for general information. I'm not sure if it's necessary or helpful to other people, but surely it will be great feature to have!

Thank you for your great work Shanapu!!

**Comment by shanapu** [comment]
yes, will do that

**Comment by shanapu** [comment]
Logging is now implemented in dev branch. When using dev branch consider this change https://forums.alliedmods.net/showpost.php?p=2465494&postcount=22
