### ISSUE TITLE
Shop Limit

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailShop#8]
Is possibile to add a limit to use 150hp item beacause some player arrive to get 600+ hp...
Thanks

**Comment by shanapu** [comment]
will implement a limit/check for that soon.

**Comment by Hexer10** [comment]
If you can the flashbangs + molotov please

**Comment by shanapu** [comment]
fixed in dev branch. please consider myjailshop dev branch required myjailbreak dev branch. take a look to the dev changelogs before updating!

**Comment by Hexer10** [comment]
Ok, thanks but i need to reset translations and configs when I update MyJailShop and MyJailBreak?

**Comment by shanapu** [comment]
no reset for configs on myjs or myjb.

If there are some new translations you can easily put them into your existing translation. Check the differ and add the new part(s). 

**example:**
[old version of translation(master)](https://github.com/shanapu/MyJailShop/blob/master/addons/sourcemod/translations/MyJailShop.phrases.txt)
[new version of translation(dev)](https://github.com/shanapu/MyJailShop/blob/dev/addons/sourcemod/translations/MyJailShop.phrases.txt)

Check for difference (new parts) https://www.diffchecker.com/DGy91GrR What is new?

Add the new parts to your existing translation.
Profit! ;D

**Comment by shanapu** [comment]
or maybe send me your translation if the language is still missing.

**Comment by Hexer10** [comment]
I've added italian translation.

**Comment by shanapu** [comment]
wanna send it to me and share it with other? so you don't have to update it handish for yourself

**Comment by Hexer10** [comment]
Ok, give me some minutes to go home and restore the prefix my.jb...  Can I send here the myshop and myjb?

**Comment by shanapu** [comment]
no hurry, you can send me both here in a zip or with https://gist.github.com/ or some other way.

btw. MyJB already got Italian translations from Elleven, but they are not merged to git.
take a look at this side http://translator.mitchdempsey.com/users/378/sourcemod_plugins
don't know if there is any improvement

Thanks!

**Comment by Hexer10** [comment]
Ok, let me send only MyShop translation.

**Comment by Hexer10** [comment]
Here you are! MyJailShop translation italian (dev)
[MyJailShop.phrases.txt](https://github.com/shanapu/MyJailShop/files/589216/MyJailShop.phrases.txt)

**Comment by shanapu** [comment]
ee83894cbe045e26d29f79e1af1c84704ac71ce5

**Comment by Hexer10** [comment]
nope!

**Comment by shanapu** [comment]
> nope!

???

**Comment by Hexer10** [comment]
Sorry in italian format is different to english I would say: (di nulla!) i think in english mean: you're welcome!

**Comment by shanapu** [comment]
ah :D
grazie mille

**Comment by shanapu** [comment]
everything is implemented. I close this.
