### ISSUE TITLE
MyJailShop command bugged.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailShop#9]
I cant do /shop and in console spam this error after updating to dev verion.
Errorlog:
`L 11/17/2016 - 18:51:57: [SM] Exception reported: Native is not bound`  
`L 11/17/2016 - 18:51:57: [SM] Blaming: MyJailShop.smx`  
`L 11/17/2016 - 18:51:57: [SM] Call stack trace:`  
`L 11/17/2016 - 18:51:57: [SM]   [1] IsEventDayRunning`  
`L 11/17/2016 - 18:51:57: [SM]   [2] Line 490, MyJailShop.sp::Command_Menu_OpenShop`  
My CVar: 
sm_jailshop_cmds_shop "jbshop,jbstore,jailstore,shop"

EDIT: Now I saw that /jailshop (/shop not)work.

**Comment by shanapu** [comment]
this error says to me you still on master branch.
`IsEventDayRunning` was renamed in dev branch to `MyJailbreak_IsEventDayRunning`

**Comment by Hexer10** [comment]
"MyJailShop" (1.1.dev) by shanapu
"MyJailbreak - Core" (Beta 8.1.develop) by shanapu
I think they are both from dev brach.

**Comment by shanapu** [comment]
oh i done a mistake on versioning. master and dev both called 1.1.dev.  I will fix that now. Master will be 1.1 and dev will be 1.2.dev

you can "easily" see on the error log that you are still on master branch.
Your error says:  in function `Command_Menu_OpenShop` in Line 490 is a error with `IsEventDayRunning`
So we investigate. 
On master on [Line 490](https://github.com/shanapu/MyJailShop/blob/master/addons/sourcemod/scripting/MyJailShop.sp#L490) we can find `IsEventDayRunning`
On dev on [line 490](https://github.com/shanapu/MyJailShop/blob/dev/addons/sourcemod/scripting/myjailshop.sp#L490) we can't find `IsEventDayRunning`. The line is also not in function `Command_Menu_OpenShop`
If we search for `IsEventDayRunning` we will find renamed in [Line 513](https://github.com/shanapu/MyJailShop/blob/dev/addons/sourcemod/scripting/myjailshop.sp#L513) as `MyJailbreak_IsEventDayRunning`

I hope i could help you to understand these error.

[here the download](https://github.com/shanapu/MyJailShop/archive/dev.zip) for dev version.

**Comment by Hexer10** [comment]
Thanks, i solved all the problems, where i can see (CVars) the new features related to this post(i can't find them):
#8

**Comment by shanapu** [comment]
fixed? can be closed?
